const languages = [
  { code: 'en', label: 'אנגלית', emoji: '🇺🇸' },
  { code: 'es', label: 'ספרדית', emoji: '🇪🇸' },
  { code: 'fr', label: 'צרפתית', emoji: '🇫🇷' },
  { code: 'de', label: 'גרמנית', emoji: '🇩🇪' },
  { code: 'zh', label: 'סינית', emoji: '🇨🇳' },
  { code: 'ja', label: 'יפנית', emoji: '🇯🇵' },
  { code: 'ko', label: 'קוריאנית', emoji: '🇰🇷' },
  { code: 'ru', label: 'רוסית', emoji: '🇷🇺' },
  { code: 'pt', label: 'פורטוגזית', emoji: '🇵🇹' },
  { code: 'it', label: 'איטלקית', emoji: '🇮🇹' },
  { code: 'ar', label: 'ערבית', emoji: '🇸🇦' },
  { code: 'hi', label: 'הינדי', emoji: '🇮🇳' },
  { code: 'bn', label: 'בנגלית', emoji: '🇧🇩' },
  { code: 'tr', label: 'טורקית', emoji: '🇹🇷' },
  { code: 'vi', label: 'וייטנאמית', emoji: '🇻🇳' },
  { code: 'pl', label: 'פולנית', emoji: '🇵🇱' },
  { code: 'nl', label: 'הולנדית', emoji: '🇳🇱' },
  { code: 'el', label: 'יוונית', emoji: '🇬🇷' },
  { code: 'he', label: 'עברית', emoji: '🇮🇱' },
  { code: 'sv', label: 'שוודית', emoji: '🇸🇪' },
];
export default languages;
